import Header from '../components/Header'
import Footer from '../components/Footer'
import './globals.css';
import { Roboto_Slab } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';
import { AppProvider } from '../context';

const inter = Roboto_Slab({ subsets: ['latin'] })

export const metadata = {
  title: 'Edvardson Sweden',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon-3c61b1.png" type="image/png" sizes="32x32" />
      </head>
      <AppProvider>
        <body className={inter.className}>
          <NextTopLoader color='#000' />
          {/* <div className='min-h-screen 
          bg-[url("/images/edvardson_bg.jpeg")] bg-fixed 
          text-grayish'> */}
          <div className='min-h-screen 
          text-grayish'>
            <Header />
            <main className='transition-all duration-100'>{children}</main>
            <Footer />
          </div>
        </body>
      </AppProvider>
    </html>
  )
}