import Header from './components/Header'
import Footer from './components/Footer'
import './globals.css';
import { Roboto_Slab } from 'next/font/google';

const inter = Roboto_Slab({ subsets: ['latin'] })

export const metadata = {
  title: 'Edvardson Sweden',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='min-h-screen bg-[url("https://shop.textalk.se/shop/21855/files/wood_bg.jpg")] text-grayish'>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}